from __future__ import annotations

import base64
import hashlib
import hmac
import json
import time

from commontrust_bot.config import settings


def _b64url_encode(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _hmac_sha256(key: bytes, msg: bytes) -> bytes:
    return hmac.new(key, msg, hashlib.sha256).digest()


def make_review_response_token(
    review_id: str,
    reviewee_telegram_id: int,
    *,
    ttl_seconds: int = 60 * 60 * 24 * 30,  # 30 days
) -> str:
    """
    Format: base64url(payload_json).base64url(hmac_sha256(secret, payload_json))

    This token is intended to be generated by the bot and verified by the Next.js web app.
    """
    secret = (settings.review_response_secret or "").strip()
    if not secret:
        raise ValueError("REVIEW_RESPONSE_SECRET is not configured")
    if not review_id or not review_id.strip():
        raise ValueError("review_id is required")
    if not isinstance(reviewee_telegram_id, int) or reviewee_telegram_id <= 0:
        raise ValueError("reviewee_telegram_id must be a positive int")

    payload = {
        "review_id": review_id,
        "reviewee_tid": reviewee_telegram_id,
        "exp": int(time.time()) + int(ttl_seconds),
    }
    payload_bytes = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
    sig = _hmac_sha256(secret.encode("utf-8"), payload_bytes)
    return f"{_b64url_encode(payload_bytes)}.{_b64url_encode(sig)}"

